# main text of home
name: Sichao He
bio: An undergraduate from Beijing Jiaotong University & the technical director of Beijing Zhinong Technology Co. LTD

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.jpg

url: http://Routhleck.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
github: Routhleck
email: 20301037@bjtu.edu.cn

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
